pmd.bat -d "D:\Addepar\GitHub\SF_LightningDataTable\src" -f html -R "category/apex/design.xml" -reportfile "D:\Addepar\GitHub\SF_LightningDataTable\docs\PMD\apex_design.html"

pmd.bat -d "D:\Addepar\GitHub\SF_LightningDataTable\src" -f html -R "category/apex/bestpractices.xml" -reportfile "D:\Addepar\GitHub\SF_LightningDataTable\docs\PMD\apex_bestpractices.html"

pmd.bat -d "D:\Addepar\GitHub\SF_LightningDataTable\src" -f html -R "category/apex/documentation.xml" -reportfile "D:\Addepar\GitHub\SF_LightningDataTable\docs\PMD\apex_documentation.html"

pmd.bat -d "D:\Addepar\GitHub\SF_LightningDataTable\src" -f html -R "category/apex/codestyle.xml" -reportfile "D:\Addepar\GitHub\SF_LightningDataTable\docs\PMD\apex_codestyle.html"

pmd.bat -d "D:\Addepar\GitHub\SF_LightningDataTable\src" -f html -R "category/apex/errorprone.xml" -reportfile "D:\Addepar\GitHub\SF_LightningDataTable\docs\PMD\apex_errorprone.html"

pmd.bat -d "D:\Addepar\GitHub\SF_LightningDataTable\src" -f html -R "category/apex/performance.xml" -reportfile "D:\Addepar\GitHub\SF_LightningDataTable\docs\PMD\apex_performance.html"

pmd.bat -d "D:\Addepar\GitHub\SF_LightningDataTable\src" -f html -R "category/apex/security.xml" -reportfile "D:\Addepar\GitHub\SF_LightningDataTable\docs\PMD\apex_security.html"

pmd.bat -d "D:\Addepar\GitHub\SF_LightningDataTable\src" -f html -R "rulesets/apex/quickstart.xml" -reportfile "D:\Addepar\GitHub\SF_LightningDataTable\docs\PMD\apex_quickstart.html"